import { Inter } from "next/font/google";
import "./globals.css";

import Provider from "./Provider";
import Login_modal from "./Component/Login/Login_modal";
import Role from "./Component/Check/Role";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider>
      <html lang="en">
        <body className={inter.className}>
          <Role />
          <Login_modal />
          {children}
        </body>
      </html>
    </Provider>
  );
}
